package cn.coreqi.server.entity;

public class ParamAuthorityType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_authority_type.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_authority_type.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_authority_type.ordernum
     *
     * @mbg.generated
     */
    private Integer ordernum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_authority_type.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_authority_type.is_url
     *
     * @mbg.generated
     */
    private Boolean isUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_authority_type.id
     *
     * @return the value of param_authority_type.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_authority_type.id
     *
     * @param id the value for param_authority_type.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_authority_type.name
     *
     * @return the value of param_authority_type.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_authority_type.name
     *
     * @param name the value for param_authority_type.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_authority_type.ordernum
     *
     * @return the value of param_authority_type.ordernum
     *
     * @mbg.generated
     */
    public Integer getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_authority_type.ordernum
     *
     * @param ordernum the value for param_authority_type.ordernum
     *
     * @mbg.generated
     */
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_authority_type.code
     *
     * @return the value of param_authority_type.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_authority_type.code
     *
     * @param code the value for param_authority_type.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_authority_type.is_url
     *
     * @return the value of param_authority_type.is_url
     *
     * @mbg.generated
     */
    public Boolean getIsUrl() {
        return isUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_authority_type.is_url
     *
     * @param isUrl the value for param_authority_type.is_url
     *
     * @mbg.generated
     */
    public void setIsUrl(Boolean isUrl) {
        this.isUrl = isUrl;
    }
}