package cn.coreqi.server.entity;

public class PmRoleAndAuthority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_role_and_authority.role_id
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_role_and_authority.authority_id
     *
     * @mbg.generated
     */
    private String authorityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_role_and_authority.role_id
     *
     * @return the value of pm_role_and_authority.role_id
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_role_and_authority.role_id
     *
     * @param roleId the value for pm_role_and_authority.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_role_and_authority.authority_id
     *
     * @return the value of pm_role_and_authority.authority_id
     *
     * @mbg.generated
     */
    public String getAuthorityId() {
        return authorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_role_and_authority.authority_id
     *
     * @param authorityId the value for pm_role_and_authority.authority_id
     *
     * @mbg.generated
     */
    public void setAuthorityId(String authorityId) {
        this.authorityId = authorityId == null ? null : authorityId.trim();
    }
}