package cn.coreqi.server.entity;

import java.time.LocalDateTime;

public class PmUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.update_time
     *
     * @mbg.generated
     */
    private LocalDateTime updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.row_version
     *
     * @mbg.generated
     */
    private LocalDateTime rowVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.login_name
     *
     * @mbg.generated
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.main_department_id
     *
     * @mbg.generated
     */
    private String mainDepartmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.sex_id
     *
     * @mbg.generated
     */
    private Integer sexId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user.is_enabled
     *
     * @mbg.generated
     */
    private Boolean isEnabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.id
     *
     * @return the value of pm_user.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.id
     *
     * @param id the value for pm_user.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.create_time
     *
     * @return the value of pm_user.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.create_time
     *
     * @param createTime the value for pm_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.update_time
     *
     * @return the value of pm_user.update_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.update_time
     *
     * @param updateTime the value for pm_user.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.row_version
     *
     * @return the value of pm_user.row_version
     *
     * @mbg.generated
     */
    public LocalDateTime getRowVersion() {
        return rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.row_version
     *
     * @param rowVersion the value for pm_user.row_version
     *
     * @mbg.generated
     */
    public void setRowVersion(LocalDateTime rowVersion) {
        this.rowVersion = rowVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.login_name
     *
     * @return the value of pm_user.login_name
     *
     * @mbg.generated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.login_name
     *
     * @param loginName the value for pm_user.login_name
     *
     * @mbg.generated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.password
     *
     * @return the value of pm_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.password
     *
     * @param password the value for pm_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.nick_name
     *
     * @return the value of pm_user.nick_name
     *
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.nick_name
     *
     * @param nickName the value for pm_user.nick_name
     *
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.main_department_id
     *
     * @return the value of pm_user.main_department_id
     *
     * @mbg.generated
     */
    public String getMainDepartmentId() {
        return mainDepartmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.main_department_id
     *
     * @param mainDepartmentId the value for pm_user.main_department_id
     *
     * @mbg.generated
     */
    public void setMainDepartmentId(String mainDepartmentId) {
        this.mainDepartmentId = mainDepartmentId == null ? null : mainDepartmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.sex_id
     *
     * @return the value of pm_user.sex_id
     *
     * @mbg.generated
     */
    public Integer getSexId() {
        return sexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.sex_id
     *
     * @param sexId the value for pm_user.sex_id
     *
     * @mbg.generated
     */
    public void setSexId(Integer sexId) {
        this.sexId = sexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user.is_enabled
     *
     * @return the value of pm_user.is_enabled
     *
     * @mbg.generated
     */
    public Boolean getIsEnabled() {
        return isEnabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user.is_enabled
     *
     * @param isEnabled the value for pm_user.is_enabled
     *
     * @mbg.generated
     */
    public void setIsEnabled(Boolean isEnabled) {
        this.isEnabled = isEnabled;
    }
}