package cn.coreqi.server.entity;

public class PmUserAndRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user_and_role.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_user_and_role.role_id
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user_and_role.user_id
     *
     * @return the value of pm_user_and_role.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user_and_role.user_id
     *
     * @param userId the value for pm_user_and_role.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_user_and_role.role_id
     *
     * @return the value of pm_user_and_role.role_id
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_user_and_role.role_id
     *
     * @param roleId the value for pm_user_and_role.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}