package cn.coreqi.server.repository.entityMapper;

import cn.coreqi.server.entity.PmRoleAndAuthority;
import cn.coreqi.server.entity.PmRoleAndAuthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmRoleAndAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_role_and_authority
     *
     * @mbg.generated
     */
    long countByExample(PmRoleAndAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_role_and_authority
     *
     * @mbg.generated
     */
    int deleteByExample(PmRoleAndAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_role_and_authority
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("roleId") String roleId, @Param("authorityId") String authorityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_role_and_authority
     *
     * @mbg.generated
     */
    int insert(PmRoleAndAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_role_and_authority
     *
     * @mbg.generated
     */
    int insertSelective(PmRoleAndAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_role_and_authority
     *
     * @mbg.generated
     */
    List<PmRoleAndAuthority> selectByExample(PmRoleAndAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_role_and_authority
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PmRoleAndAuthority record, @Param("example") PmRoleAndAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_role_and_authority
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PmRoleAndAuthority record, @Param("example") PmRoleAndAuthorityExample example);
}