package cn.coreqi.server.repository.entityMapper;

import cn.coreqi.server.entity.PmUser;
import cn.coreqi.server.entity.PmUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbg.generated
     */
    long countByExample(PmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbg.generated
     */
    int deleteByExample(PmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbg.generated
     */
    int insert(PmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbg.generated
     */
    int insertSelective(PmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbg.generated
     */
    List<PmUser> selectByExample(PmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbg.generated
     */
    PmUser selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PmUser record, @Param("example") PmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PmUser record, @Param("example") PmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PmUser record);
}